name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

env:
  APP_NAME: registration
  # Location of the phpunit.xml and phpunit.integration.xml files
  # Comment to disable
  PHPUNIT_CONFIG: ./tests/phpunit.xml
  # PHPUNIT_INTEGRATION_CONFIG: ./tests/phpunit.integration.xml

jobs:
  phpunit-sqlite:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['7.4']
        databases: ['sqlite']
        server-versions: ['master', 'stable23', 'stable22']
        include:
          - php-versions: '7.3'
            server-versions: 'stable22'
            databases: 'sqlite'

    steps:
      - name: Checkout server
        uses: actions/checkout@v2
        with:
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite
          coverage: none

      - name: Set up PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass password
          ./occ app:enable --force ${{ env.APP_NAME }}
          php -S localhost:8080 &

      - name: PHPUnit
        # Only run if phpunit config file exists
        if: env.PHPUNIT_CONFIG != ''
        working-directory: apps/${{ env.APP_NAME }}
        run: ./vendor/phpunit/phpunit/phpunit -c ${{ env.PHPUNIT_CONFIG }}

      - name: PHPUnit integration
        # Only run if phpunit integration config file exists
        if: env.PHPUNIT_INTEGRATION_CONFIG != ''
        working-directory: apps/${{ env.APP_NAME }}
        run: ./vendor/phpunit/phpunit/phpunit -c ${{ env.PHPUNIT_INTEGRATION_CONFIG }}

  summary:
    runs-on: ubuntu-latest
    needs: phpunit-sqlite

    if: always()

    name: phpunit-sqlite-summary

    steps:
      - name: Summary status
        run: if ${{ needs.phpunit-sqlite.result != 'success' }}; then exit 1; fi
